version: '3.7'

services:
    mysqldb:
        image: mysql:5.7
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=ptitbiomed
        ports:
            - "3306:3306"
        volumes:
            - db:/var/lib/mysql
    app:
        image: apleb-app:0.0.2-SNAPSHOT
        depends_on:
            - mysqldb
        ports:
            - "8080:8080"
        volumes:
            - .m2:/root/.m2
        stdin_open: true
        tty: true

volumes:
    db:
