spring:
    datasource:
        driver-class-name: org.mariadb.jdbc.Driver

    jpa:
        hibernate:
            ddl-auto: validate
        properties:
            hibernate:
                dialect: org.hibernate.dialect.MariaDBDialect

    liquibase:
        change-log: classpath:db/changelog/changelog.xml

    servlet:
        multipart:
            max-file-size: 128MB
            max-request-size: 128MB
            enabled: true
